# **Uploading Files**

In [ ]:
#上傳檔案方法一 : 直接upload
from google.colab import files
files.upload()              # 上傳檔案

In [1]:
#上傳檔案方法二 : 從google drive
from google.colab import drive
import pandas as pd
import numpy as np
drive.mount('/content/gdrive') # 此處需要登入google帳號
# 獲取授權碼之後輸入即可連動雲端硬碟
data_sep = pd.read_csv("/content/gdrive/My Drive/玉山NLP_自己/word_df(2).csv", encoding = 'utf-8')
data_all = pd.read_csv("/content/gdrive/My Drive/玉山NLP_自己/news_df_2.csv")
data_crime = pd.read_excel("/content/gdrive/My Drive/玉山NLP_自己/news_crime.xlsx")
data_nocrime = pd.read_excel("/content/gdrive/My Drive/玉山NLP_自己/news_nocrime.xlsx")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [ ]:
#查看現在colab裡面有什麼檔案
!ls

gdrive	sample_data


# **Data Preprocessing**

In [12]:
data_all #全部的新聞

news_ID  ...                                            content
0        3681  ...  TFT-LCD液晶面板產業淘汰賽持續進行。儘管8K、OLED、MicroLED持續為顯示器產...
1        3247  ...  美中貿易衝突持續，美國國會反中聲浪延燒，共和與民主黨參議員聯手提出法案，阻止美國聯邦退休基金...
2        2561  ...  10元是日常生活中廣泛應用的硬幣，但多數民眾可能沒有好好端詳過硬幣究竟暗藏哪些玄機，中央銀行...
3         959  ...  LGDisplayCoLtd（簡稱：LGD）7月23日公布2019年第二季（截至6月30日）...
4        3005  ...  Google母公司Alphabet公布第二季財報，營收達389.4億美元，每股盈餘14.21...
...       ...  ...                                                ...
4956     1530  ...  證交所正式公告「109年度（第七屆）公司治理評鑑指標」 證交所正式公告「109年度（第七屆）...
4957     1766  ...  證期雙分析師陳韋霖應自2014年開始利用證券公司貴賓室開課 證期雙分析師陳韋霖應自2014年...
4958     4634  ...  寶德資訊負責人曾昭榮以圈購誠品書店、台灣大車隊等未上市、櫃股票為利誘，僱用業務員騙過上千名被...
4959     4645  ...  繼上月初國內五家電信業者向NCC完成5G頻譜投標遞件之後 繼上月初國內五家電信業者向NCC完...
4960      825  ...  繼保良局陳守仁小學資料庫疑遭黑客入侵後 繼保良局陳守仁小學資料庫疑遭黑客入侵後，再有熱門直資...

[4961 rows x 4 columns]

In [13]:
data_nocrime = data_all[data_all['name'] == '[]' ]
#只有"有犯罪人名"的新聞

In [14]:
data_nocrime

news_ID  ...                                            content
0        3681  ...  TFT-LCD液晶面板產業淘汰賽持續進行。儘管8K、OLED、MicroLED持續為顯示器產...
1        3247  ...  美中貿易衝突持續，美國國會反中聲浪延燒，共和與民主黨參議員聯手提出法案，阻止美國聯邦退休基金...
2        2561  ...  10元是日常生活中廣泛應用的硬幣，但多數民眾可能沒有好好端詳過硬幣究竟暗藏哪些玄機，中央銀行...
3         959  ...  LGDisplayCoLtd（簡稱：LGD）7月23日公布2019年第二季（截至6月30日）...
4        3005  ...  Google母公司Alphabet公布第二季財報，營收達389.4億美元，每股盈餘14.21...
...       ...  ...                                                ...
4949     4998  ...  108年全國運動會聖火傳遞17日下午來到桃園市大園區公所，由大園區長徐藍科率行政團隊，從圳頭...
4954     5011  ...  831示威港九新界、地上地下的水火警民衝突，水炮車和汽油彈在多處交戰，警方和示威者在港鐵站激...
4956     1530  ...  證交所正式公告「109年度（第七屆）公司治理評鑑指標」 證交所正式公告「109年度（第七屆）...
4959     4645  ...  繼上月初國內五家電信業者向NCC完成5G頻譜投標遞件之後 繼上月初國內五家電信業者向NCC完...
4960      825  ...  繼保良局陳守仁小學資料庫疑遭黑客入侵後 繼保良局陳守仁小學資料庫疑遭黑客入侵後，再有熱門直資...

[4617 rows x 4 columns]

In [ ]:
data_sep #斷好詞的新聞

X1     word        word_pos  word_loca  news_id
0         0  TFT-LCD              FW          1     3681
1         0       液晶              Na          2     3681
2         0       面板              Na          3     3681
3         0       產業              Na          4     3681
4         0      淘汰賽              Na          5     3681
...      ..      ...             ...        ...      ...
2565297   0       資料              Na        359      825
2565298   0       私隱              Na        360      825
2565299   0       專員              Na        361      825
2565300   0       公署             ORG        362      825
2565301   0        。  PERIODCATEGORY        363      825

[2565302 rows x 5 columns]

In [ ]:
data_sep = data_sep[data_sep['word_pos'] != 'PER']

In [ ]:
data

X1     word        word_pos  word_loca  news_id
0         0  TFT-LCD              FW          1     3681
1         0       液晶              Na          2     3681
2         0       面板              Na          3     3681
3         0       產業              Na          4     3681
4         0      淘汰賽              Na          5     3681
...      ..      ...             ...        ...      ...
2565297   0       資料              Na        359      825
2565298   0       私隱              Na        360      825
2565299   0       專員              Na        361      825
2565300   0       公署             ORG        362      825
2565301   0        。  PERIODCATEGORY        363      825

[2528175 rows x 5 columns]

In [16]:
data_crime = data_all[data_all['name'] != '[]' ]
data_crime

news_ID  ...                                            content
65       4659  ...  香港海關本周三(23日)於機場入境大堂，例行檢查2名從秘魯利馬出發，經法國巴黎轉機抵港的男女...
102      4064  ...  各地政府聯手打擊本港黑幫和勝和前坐館泰國大毒梟「上海仔」郭永鴻的販毒集團，令毒販趁「末日」前...
104      4471  ...  越南警方近日在河內、胡志明、慶和等省市偵破一個大型網上賭博集團，涉案的投注金額高達30兆越南...
114      1159  ...  屏科大客研所教授郭訓德涉嫌虛報差旅費及採購費，詐領公款400多萬元，屏東地院併處他9個月徒刑...
115      3642  ...  立法院前秘書長林錫山，被控收受網遠科技二千八百萬元賄款，共被判刑三十六年定讞，未來將由檢方向...
...       ...  ...                                                ...
4952     3345  ...  馥貴生技美食公司負責人高新，在林口、台中開設藥膳料理餐廳，藉由舉辦試吃會，並打著迪化街中藥材...
4953     3748  ...  藝人侯佩岑代言的「英倫產後護理之家」所屬於京倫集團，董事長李俊琳、胡白玫夫妻被新加坡籍李姓女...
4955     1842  ...  藝人徐乃麟在內湖區購買的「米蘭苑」豪宅詐賭案，被告楊強蓉被士林地檢署認為罪證不足，予以不起訴...
4957     1766  ...  證期雙分析師陳韋霖應自2014年開始利用證券公司貴賓室開課 證期雙分析師陳韋霖應自2014年...
4958     4634  ...  寶德資訊負責人曾昭榮以圈購誠品書店、台灣大車隊等未上市、櫃股票為利誘，僱用業務員騙過上千名被...

[344 rows x 4 columns]

In [17]:
#把新聞貼回去(全部)
news_list = []
for i in data_all.news_ID:
    news_list.append(i)

num_news = len(news_list)

news = []
for i in news_list:
    search_id = i
    temp = []
    temp_news = data_sep[data_sep['news_id'] == search_id].word 
    for j in temp_news:
        temp.append(str(j))
    news.append(temp)    

In [18]:
#把新聞貼回去(nocrime)
news_list_nocrime = []
for i in data_nocrime.news_ID:
    news_list_nocrime.append(i)

news_nocrime = []
for i in news_list_nocrime:
    search_id = i
    temp = []
    temp_news = data_sep[data_sep['news_id'] == search_id].word 
    for j in temp_news:
        temp.append(str(j))
    news_nocrime.append(temp)    

In [19]:
#把新聞貼回去(crime)
news_list_crime = []
for i in data_crime.news_ID:
    news_list_crime.append(i)

news_crime = []
for i in news_list_crime:
    search_id = i
    temp = []
    temp_news = data_sep[data_sep['news_id'] == search_id].word 
    for j in temp_news:
        temp.append(str(j))
    news_crime.append(temp) 

In [20]:
stopword = []
with open('/content/gdrive/My Drive/玉山NLP_自己/stopword.txt', 'r', encoding = 'utf8') as file:
  for data in file.readlines():
    data = data.strip()
    stopword.append(data)

In [21]:
def del_stopword(word_list):
  news_list = word_list.copy()
  for i in range(len(word_list)):
    news_list[i] = []
    for j in range(len(word_list[i])):
      if word_list[i][j] not in stopword:
        news_list[i].append(word_list[i][j])
  return news_list

In [22]:
news_nocrime_stop = del_stopword(news_nocrime)
news_crime_stop = del_stopword(news_crime)
news_stop = del_stopword(news)


In [23]:
corpus_crime = []
for i in range(len(news_crime_stop)):
    corpus_crime.append(' '.join(news_crime_stop[i]))

In [ ]:
corpus_crime

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=CountVectorizer()
transformer=TfidfTransformer()
tfidf=transformer.fit_transform(vectorizer.fit_transform(corpus_crime))
word=vectorizer.get_feature_names()
weight=tfidf.toarray()


In [ ]:
import heapq
#不對的方法
tfidf_list = []
for i in range(len(weight)):
  list_word = [] 
  a = weight[i].tolist()
  max_num_index_list = map((a).index, heapq.nlargest(10, a))
  for j in list(max_num_index_list):
    list_word.append(word[j])
  tfidf_list.append(list_word)

In [26]:
tfidf_list_10 = []
for i in range(len(weight)):
  list_word = [] 
  a = weight[i].tolist()
  b = sorted(enumerate(a), key=lambda x:x[1], reverse = True)
  index_list = []
  value_list = []
  for index, value in b:
    index_list.append(index)
  for j in index_list[:10]:
    list_word.append(word[j])  
  tfidf_list_10.append(list_word)

In [53]:
tfidf_list_10

[['入境', '大堂', '提堂', '液態', '男女', '23日', '香港', '22', '機場', '海關'],
 ['上海仔', '警方', '越南', '泰國', '冰毒', '毒案', '破獲', '毒品', '胡志明市', '拘捕'],
 ['賭博', '當局', '平台', '越南', '其後', '大型', '邱浩成', '賭博罪', '拘捕', '台灣籍'],
 ['郭訓德', '屏科大', '公款', '虛報差', '會計法', '併處', '旅費', '校方', '教授', '400多萬'],
 ['林錫山', '網遠', '財產', '收賄', '標案', '高院', '秘書長', '二千八百萬', '資訊', '立法院'],
 ['許國楨', '林嫌', '士兵', '申辦', '詐財', '廣告', '提早', '被害人', 'fb', '廣發'],
 ['玖地', '徐仲榮', '購併', '陳仕修', '黃國昌', '基金', '500萬', '國發', '展現', '庄吉'],
 ['貴婦奈奈', '奈奈', '貴婦', '房子', '豪宅', '家人', '公公', '成謎', '蘇陳端', '部落客'],
 ['蘇清俊', '監獄', '受刑人', '典獄長', '北監', '池泳霖', '特權', '獄官', '王令麟', '黑道'],
 ['俞小凡', '詐騙', '人民幣', '車手', '連帶', '845萬', '專線', '賠償', '集團', '公安'],
 ['民眾', '廢收據', '窗口', '監理所', '電腦', '書記', '生手', '中檢', '催繳', '繳回'],
 ['江男', '工程', '鍾婦', '裝修', '業主', '蔡世誠', '施工', '簽約', '59萬5千', '設計'],
 ['投票權', '賴文德', '11月', '選區', '里長', '選民', '交付', '3000', '具有', '買票'],
 ['檢疫', '漁船', '魚貨', '走私', '陳澤信', '公斤', '中國', '5000餘', '台南安平港', '振瑞發'],
 ['美亞', '交保', '黃春發', '掏空', '300萬', '離開', '林亨標', '黃捷', '大亨',

In [27]:
tfidf_list_5 = []
for i in range(len(weight)):
  list_word = [] 
  a = weight[i].tolist()
  b = sorted(enumerate(a), key=lambda x:x[1], reverse = True)
  index_list = []
  value_list = []
  for index, value in b:
    index_list.append(index)
  for j in index_list[:5]:
    list_word.append(word[j])  
  tfidf_list_5.append(list_word)

In [54]:
tfidf_list_5

[['大堂', '提堂', '液態', '入境', '男女'],
 ['上海仔', '警方', '越南', '泰國', '冰毒'],
 ['賭博', '當局', '越南', '平台', '其後'],
 ['郭訓德', '屏科大', '公款', '虛報差', '併處'],
 ['林錫山', '網遠', '收賄', '標案', '秘書長'],
 ['許國楨', '林嫌', '士兵', '提早', '詐財'],
 ['玖地', '徐仲榮', '購併', '陳仕修', '黃國昌'],
 ['貴婦奈奈', '奈奈', '貴婦', '房子', '豪宅'],
 ['蘇清俊', '監獄', '受刑人', '典獄長', '北監'],
 ['俞小凡', '詐騙', '人民幣', '車手', '連帶'],
 ['廢收據', '民眾', '窗口', '監理所', '電腦'],
 ['江男', '鍾婦', '工程', '裝修', '業主'],
 ['投票權', '賴文德', '里長', '選區', '11月'],
 ['檢疫', '魚貨', '漁船', '走私', '陳澤信'],
 ['美亞', '交保', '黃春發', '300萬', '掏空'],
 ['卡西酮', '緝毒', '毒品', '單位', '公斤'],
 ['司機', '傾倒', '廢棄物', '砂石車', '張男'],
 ['安毒', '器具', '邱俊福', '零件', '夾藏'],
 ['孫玦新', '邱希庚', '欣桃', '獎金', '薪資'],
 ['陳星佑', '碳酸鎂', '陳鏡如', '工業', '椒鹽粉'],
 ['林文楨', '桃園', '工程師', '工程', '機場'],
 ['鄒德道', '申設', '黃男', '產業', 'bmw'],
 ['大飲', '國信', '孫幼英', '旭順', '林偉強'],
 ['廠商', '趙宏翰', '鄉長', '工程', '大武'],
 ['鄭俊宏', '羅姓', '塗女', '塗姓', '羅男'],
 ['吳男', '美金', '主管', '千禧', '陳宣銘'],
 ['吳松薰', '屏東縣議會', '李立法', '秘書長', '廉政署'],
 ['陳婦', '往生', '互助會', '福佑', '會員'],
 ['繆竹怡', '歸案', '調查局', '

In [29]:
crime_word_10 = []
for i in range(len(tfidf_list_10)):
  for j in range(len(tfidf_list_10[i])):
    crime_word_10.append(tfidf_list_10[i][j])

In [ ]:
crime_word_10

In [30]:
crime_word_5 = []
for i in range(len(tfidf_list_5)):
  for j in range(len(tfidf_list_5[i])):
    crime_word_5.append(tfidf_list_5[i][j])

In [ ]:
crime_word_5

900

# **Modeling**

## train : crime - 100% , tfidf 取前5

In [31]:
wrong_count_list = []
for i in range(len(news_nocrime_stop)):
  count = 0
  for j in range(len(news_nocrime_stop[i])):
    if news_nocrime_stop[i][j] in crime_word_5:
      count += 1
  wrong_count_list.append(count)   

In [ ]:
wrong_count_list

In [32]:
count_nonzero = 0
for i in wrong_count_list:
  if i != 0:
    count_nonzero += 1
print(len(wrong_count_list) - count_nonzero) #正確的數目
print(count_nonzero) #錯誤的數目
print(len(wrong_count_list)) #全部的新聞量

'''
13
4604
4617
'''

13
4604
4617


## train : crime - 100% , tfidf 取前10

In [33]:
wrong_count_list = []
for i in range(len(news_nocrime_stop)):
  count = 0
  for j in range(len(news_nocrime_stop[i])):
    if news_nocrime_stop[i][j] in crime_word_10:
      count += 1
  wrong_count_list.append(count)  

count_nonzero = 0
for i in wrong_count_list:
  if i != 0:
    count_nonzero += 1
print(len(wrong_count_list) - count_nonzero) #正確的數目
print(count_nonzero) #錯誤的數目
print(len(wrong_count_list)) #全部的新聞量 

'''
3
4614
4617
'''

3
4614
4617


## 拿50%有犯罪的新聞去測剩下50%有犯罪的新聞看抓的到幾篇 , tfidf 取前10

In [ ]:
from sklearn.model_selection import train_test_split

In [39]:
#344 * 0.5 = 172
data_crime_A = data_crime[:172]
data_crime_B = data_crime[172:]

In [41]:
#把新聞貼回去(A)
news_list_crime_A = []
for i in data_crime_A.news_ID:
    news_list_crime_A.append(i)

news_crime_A = []
for i in news_list_crime_A:
    search_id = i
    temp = []
    temp_news = data_sep[data_sep['news_id'] == search_id].word 
    for j in temp_news:
        temp.append(str(j))
    news_crime_A.append(temp) 

In [43]:
#把新聞貼回去(B)
news_list_crime_B = []
for i in data_crime_B.news_ID:
    news_list_crime_B.append(i)

news_crime_B = []
for i in news_list_crime_B:
    search_id = i
    temp = []
    temp_news = data_sep[data_sep['news_id'] == search_id].word 
    for j in temp_news:
        temp.append(str(j))
    news_crime_B.append(temp) 

In [44]:
news_crime_A_stop = del_stopword(news_crime_A)
news_crime_B_stop = del_stopword(news_crime_B)

In [46]:
corpus_crime_A = []
for i in range(len(news_crime_A_stop)):
    corpus_crime_A.append(' '.join(news_crime_A_stop[i]))

In [47]:
vectorizer=CountVectorizer()
transformer=TfidfTransformer()
tfidf=transformer.fit_transform(vectorizer.fit_transform(corpus_crime_A))
word=vectorizer.get_feature_names()
weight=tfidf.toarray()

In [48]:
tfidf_list_10 = []
for i in range(len(weight)):
  list_word = [] 
  a = weight[i].tolist()
  b = sorted(enumerate(a), key=lambda x:x[1], reverse = True)
  index_list = []
  value_list = []
  for index, value in b:
    index_list.append(index)
  for j in index_list[:10]:
    list_word.append(word[j])  
  tfidf_list_10.append(list_word)

In [49]:
crime_word_10 = []
for i in range(len(tfidf_list_10)):
  for j in range(len(tfidf_list_10[i])):
    crime_word_10.append(tfidf_list_10[i][j])

In [51]:
wrong_count_list = []
for i in range(len(news_crime_B_stop)):
  count = 0
  for j in range(len(news_crime_B_stop[i])):
    if news_crime_B_stop[i][j] in crime_word_10:
      count += 1
  wrong_count_list.append(count)   

In [52]:
count_nonzero = 0
for i in wrong_count_list:
  if i != 0:
    count_nonzero += 1
print(len(wrong_count_list) - count_nonzero) #正確的數目
print(count_nonzero) #錯誤的數目
print(len(wrong_count_list)) #全部的新聞量
'''
0
172
172
'''

0
172
172


# **測試Code**

In [ ]:
t = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

In [ ]:
vectorizer = CountVectorizer()
#计算个词语出现的次数
X = vectorizer.fit_transform(t)
#获取词袋中所有文本关键词
word = vectorizer.get_feature_names()
print(word)
#查看词频结果
print(X.toarray())
 
from sklearn.feature_extraction.text import TfidfTransformer
 
#类调用
transformer = TfidfTransformer()
print(transformer)
#将词频矩阵X统计成TF-IDF值
tfidf = transformer.fit_transform(X)
#查看数据结构 tfidf[i][j]表示i类文本中的tf-idf权重
print(tfidf.toarray())


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]
TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)
[[0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]
 [0.         0.27230147 0.         0.27230147 0.         0.85322574
  0.22262429 0.         0.27230147]
 [0.55280532 0.         0.         0.         0.55280532 0.
  0.28847675 0.55280532 0.        ]
 [0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]]


In [ ]:
feature_array = np.array(vectorizer.get_feature_names())
tfidf_sorting = np.argsort(tfidf.toarray()).flatten()[::-1]

n = 10
top_n = feature_array[tfidf_sorting][:n]
top_n

array(['first', 'this', 'is', 'document', 'the', 'third', 'second', 'one',
       'and', 'third'], dtype='<U8')

[2, 1, 1]
[0, 0, 0]


In [ ]:
np.argsort(tfidf.toarray())

array([[0, 4, 5, 7, 6, 1, 3, 8, 2],
       [0, 2, 4, 7, 6, 1, 3, 8, 5],
       [1, 2, 3, 5, 8, 6, 0, 4, 7],
       [0, 4, 5, 7, 6, 1, 3, 8, 2]])

In [ ]:
np.argsort(tfidf.toarray()).flatten()[::]

2

In [ ]:
top_n

array(['first', 'this', 'is'], dtype='<U8')

In [ ]:
tfidf.toarray()[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [ ]:
str = 'tree cat travellers fruit jupiter'
response = tfidf.transform([str])
feature_names = tfidf.get_feature_names()

for col in response.nonzero()[1]:
    print(feature_names[col], ' - ', response[0, col])

In [ ]:
vectorizer.fit_transform(t.split(" "))

<93x69 sparse matrix of type '<class 'numpy.int64'>'
	with 91 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf=transformer.fit_transform(vectorizer.fit_transform(t.split(" ")))

In [ ]:
tfidf.toarray()[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [ ]:
len(t.split(" "))

93

In [ ]:
response.toarray() #是照BOW裡面字的順序排(不是corpus的順序)，BOW有69個字

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.51746148, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.51746148, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.51746148,
        0.44350971, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [ ]:
tfs.toarray()[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [ ]:
feature_names[13]

'fruit'

In [ ]:
response[0,13]

0.5174614751013837

In [ ]:
response.nonzero()[1]

array([55, 54, 20, 13], dtype=int32)

In [ ]:
len(response.toarray()[0])

69